### ISSUE TITLE
Randomizing the gene that gets mutated

### ISSUE THREAD

**Issue by ngupta23** [ahmedfgad/GeneticAlgorithmPython#2]
It looks like your code (function - mutation) is mutating the same gene(s) each time. Should this not be randomized?

**Comment by ahmedfgad** [comment]
Thanks for such a nice note.
It is better to be randomized as you said. I noted that in the tutorials about genetic algorithm and applied randomized gene selection in later implementations but here it is not.

**Comment by urowietu** [comment]
This is my solution. It asks for a constant ```how_many_mut```. I’m still optimising it for Cython so it’s not perfect. I don’t know how to submit it otherwise Dr Gad - still learning github. 

def mutation(offspring_crossover):
# Mutation changes a single gene in each offspring randomly.
    for idx in range(offspring_crossover.shape[0]):
        for m in range(how_many_mut):
            # one of n=mutes random values to be added to the gene.
            random_value = np.random.uniform(-20.0, 20.0, 1)
            which_gene_mutates = randrange(num_weights)
            offspring_crossover[idx, which_gene_mutates] = offspring_crossover[idx,
which_gene_mutates] + random_value
    return offspring_crossover

**Comment by ahmedfgad** [comment]
Hello,

Some major changes are applied to the project and it supports different types of mutation and crossover operators. Randomization of gene selection is introduced. 

Based on this project, a library named PyGAD is available at PyPI: https://pypi.org/project/pygad
