### ISSUE TITLE
Check for range of values

### ISSUE THREAD

**Issue by ngupta23** [ahmedfgad/GeneticAlgorithmPython#3]
Inside the mutation function, you are adding random values to the genes. This can cause the gene values to drift over time and in one of my examples, it is causing the value to go beyond the initial range of [-4, 4]. 

Maybe some checks need to be added for the range of acceptable values for example, instead of adding a random value between -1 and 1, maybe you can just pick a random value from the original range and use that as the mutated value.

**Comment by ahmedfgad** [comment]
If there is a need for restricting the range, just do it simply by making a check. I have no restriction to make every gene falls between -4 and +4.
According to your suggested way to do that change, I discourage it because mutation is to slightly modify the current gene value to return a new value. The old and new values should be close.
Say that the current value is 0.1, then we can slightly change it to go above or below 0.1. In my case, I add a value between -1 and +1 and thus the greatest value for 0.1 is to be 0.1+1=1.1 and the smallest value is 0.1-1=0.9.
Based on your suggestion to discard the previous gene value and select a new value between -4 and +4, the new value for the 0.1 gene might be  4.1 which is much different compared to the old value 0.1.

**Comment by ngupta23** [comment]
OK, that was my initial thought as well. Thanks for confirming. I will add the range check to my code but make sure that the mutation is small compared to the original genes.
