### ISSUE TITLE
You recommend pip3 for linux and mac, but pip for windows.  Why?

### ISSUE THREAD

**Issue by StoneCypher** [ahmedfgad/GeneticAlgorithmPython#32]
If it's `pip3` anywhere, it's `pip3` everywhere.  Windows gets `pip3` from `python3` just like everybody else

**Comment by ahmedfgad** [comment]
Thank you! I usually use `pip` for Python3 in Windows which makes no issue. For Linux/Mac, pip never works for Python3.
I will update the documentation to reflect upon that soon.

**Comment by rengel8** [comment]
For me it does not make any difference on Windows to use **pip -V** oder **pip3 -V** is resolved by the same version. Linux still has python 2.x under the hood, as far as I know, why it does make sense to be sure in choosing the right instance of a package manager. Whilst working with env this might again be not that important, since the env's version is used.

**Comment by ahmedfgad** [comment]
The documentation of the latest release of PyGAD 2.14.0 is updated to only use `pip3`.
