### ISSUE TITLE
generation callback not executed properly, leads to unwanted repition of fitness function

### ISSUE THREAD

**Issue by akettring** [ahmedfgad/GeneticAlgorithmPython#38]
Working with 'pygad.kerasga' (other flavors not tested). Only one line of the callback_generation() function is executed with each generation. The number of lines in callback_generation() function determines number of times fitness_function() is repeated (unexpectedly). 

Set a global counter inside fitness function to prove this:
```
count=0
def fitness_func(solution, sol_idx):
    global count
    count += 1
    print(count)
```

Expected number of iterations:
```
callback_generation():
    print("Generation = {generation}".format(generation=ga_instance.generations_completed))
    #print("Fitness    = {fitness}".format(fitness=ga_instance.best_solution()[1]))
```

2X wasted cycles
```
callback_generation():
    print("Generation = {generation}".format(generation=ga_instance.generations_completed))
    print("Fitness    = {fitness}".format(fitness=ga_instance.best_solution()[1]))
```
fitness_func runs n_times
Prints "Generation..."
fitness_func runs n_times
Prints "Fitness..."

... and so on. Adding more lines of code multiplies the wasted cycles.

EDIT: I believe there is an additional cycle executed at the beginning of the ga_instance resulting n+1 cycles, this is on top of the bug as described above.

**Comment by ahmedfgad** [comment]
There is nothing wrong. Just let me explain how things are calculated.

Given that there are **N** solutions in the population, then internally to `PyGAD` the fitness function `fitness_func()` will be called **N** times, once for each solution.

Inside the `callback_generation()` function, the first line executed does not make the fitness function to be called at all. So, the number of times `fitness_func()` is called is still **N**.

The second line in `callback_generation()` calls the `best_solution()` method which in turn calls `fitness_func()`. So, for each of the N solutions, `fitness_func()` is called twice in the generation, one internally to PyGAD and another by the `best_solution()`. So, the total number of calls is 2N.

Note that there is an attribute called `last_generation_fitness` which holds the fitness values of the last generation. You can use it rather than calling `best_solution()`.

I hope this makes things clear.

**Comment by akettring** [comment]
That's very helpful! Thank you and sorry for the confusion. I appreciate the response and love the project!
